import "./globals.css";
import Storeprovider from "@/components/custom/storeprovider";

export const metadata = {
  title: "Garena Topup Center",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {



  return (
    <html lang="en">
      <body className="font-custom">
        <Storeprovider>{children}</Storeprovider>
      </body>
    </html>
  );
}
